# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# fail_fast: true
# exclude: include/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        args: [--style=file]
        types_or: [c++, c, cuda]
